sudo: false
dist: trusty
language: node_js
node_js: lts/*
cache:
  bundler: true
  pip: true
  npm: true
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm ci
# the next command is to fix "SSLContext object is not available" error in awscli install
- travis_retry pyenv global 3.6
- travis_retry pip install awscli --upgrade --user
script:
- npm run test